### PR TITLE
Standardized Readme

### PR DESCRIPTION
**Pull request by RichardLitt**
See multiformats/multiformats#13

Any ideas for the install and usage section, @parkan?

### CODE REVIEW

**Comment by parkan** [comment]
There's really 2 ways:
- install from sonatype: easy, but there's no CI pushing builds to them right now, so this will be outdated)

``` scala
// in Build.scala
resolvers ++= Seq(
  Resolver.sonatypeRepo("public")
)

libraryDependencies ++= Seq(
 "io.mediachain" %% "multihash" % "0.1-SNAPSHOT"
)
```
- use as subproject: not ideal but works directly with whatever is on GitHub

``` scala
val scalaMultihashCommit = "b2999d6c00b3acab6ea3ff5d0965634bed3a3823" // or w/e
lazy val scalaMultihash = RootProject(uri(
s"git://github.com/mediachain/scala-multihash.git#$scalaMultihashCommit"

lazy val MyProject = Project(...).dependsOn(scalaMultihash)
```

The real solution is probably to do #6 and then publish to sonatype from travis

/cc @yusefnapora

**Comment by yusefnapora** [comment]
good call on the automated test and publish flow.  I'll try to make time to set that up this week

**Comment by RichardLitt** [comment]
@yusefnapora Any news on the automated test and publish flow? I would love to be able to add something to the README about install; could add the comment above, too.

**Comment by parkan** [comment]
@RichardLitt we've drifted away from this a bit since our primary node is in go/libp2p now, but we'll merge + update this later today 😄

**Comment by yusefnapora** [comment]
yeah, sorry about that 😄

**Comment by RichardLitt** [comment]
hah, no worries! Thanks guys.

**Review by yusefnapora — APPROVED** [review]
@RichardLitt I added some install and usage info.  Feel free to merge if it looks alright :)

**Comment by RichardLitt** [comment]
Looks great! Thanks.

**Pull request merged**
